## <center>Devoir 11 IFT2125-A-H19</center>

**Student**: Qiang Ye (20139927) 

**Date**: 5 Avril 2019

mailto: samuel.ducharme@umontreal.ca
<hr>

**Question**
1. Soit G le graphe suivant donné par sa matrice d’adjacences pondérées.
\begin{bmatrix}
0 & \infty & 1 & 6 & 4\\
1 & 0 & \infty & \infty & 5\\
\infty & \infty & 0 & 1 & 5\\
\infty & 5 & \infty & 0 & 1\\
\infty & 2 & \infty & 3 & 0\\
\end{bmatrix}

    Utilisez l’algorithme de Floyd pour remplir les tableaux en mettant dans la case $(i, j)$ une paire de valeur $(d, k)$, où d est la distance de $i$ à $j$ et $k$ est le dernier sommet qui fait
diminuer cette distance quand l’algorithme permet de passer par lui. Montrez toutes les
itérations - c’est pourquoi vous avez cinq tableaux.
<hr>


**Answer**

Itération1
\begin{bmatrix}
[0, 0]& [\infty, 0]& [1, 0]& [6, 0]& [4, 0] \\
[1, 0]& [0, 0]& [2, 1]& [7, 1]& [5, 0] \\
[\infty, 0]& [\infty, 0]& [0, 0]& [1, 0]& [5, 0] \\
[\infty, 0]& [5, 0]& [\infty, 0]& [0, 0]& [1, 0] \\
[\infty, 0]& [2, 0]& [\infty, 0]& [3, 0]& [0, 0] \\
\end{bmatrix}


Itération2
\begin{bmatrix}
[0, 0]& [\infty, 0]& [1, 0]& [6, 0]& [4, 0]& \\
[1, 0]& [0, 0]& [2, 1]& [7, 1]& [5, 0]& \\
[\infty, 0]& [\infty, 0]& [0, 0]& [1, 0]& [5, 0]& \\
[6, 2]& [5, 0]& [7, 2]& [0, 0]& [1, 0]& \\
[3, 2]& [2, 0]& [4, 2]& [3, 0]& [0, 0]& \\
\end{bmatrix}

Itération3
\begin{bmatrix}
[0, 0]& [\infty, 0]& [1, 0]& [2, 3]& [4, 0]& \\
[1, 0]& [0, 0]& [2, 1]& [3, 3]& [5, 0]& \\
[\infty, 0]& [\infty, 0]& [0, 0]& [1, 0]& [5, 0]& \\
[6, 2]& [5, 0]& [7, 2]& [0, 0]& [1, 0]& \\
[3, 2]& [2, 0]& [4, 2]& [3, 0]& [0, 0]& \\
\end{bmatrix}

Itération4
\begin{bmatrix}
[0, 0]& [7, 4]& [1, 0]& [2, 3]& [3, 4]& \\
[1, 0]& [0, 0]& [2, 1]& [3, 3]& [4, 4]& \\
[7, 4]& [6, 4]& [0, 0]& [1, 0]& [2, 4]& \\
[6, 2]& [5, 0]& [7, 2]& [0, 0]& [1, 0]& \\
[3, 2]& [2, 0]& [4, 2]& [3, 0]& [0, 0]& \\
\end{bmatrix}

Itération5
\begin{bmatrix}
[0, 0]& [5, 5]& [1, 0]& [2, 3]& [3, 4]& \\
[1, 0]& [0, 0]& [2, 1]& [3, 3]& [4, 4]& \\
[5, 5]& [4, 5]& [0, 0]& [1, 0]& [2, 4]& \\
[4, 5]& [3, 5]& [5, 5]& [0, 0]& [1, 0]& \\
[3, 2]& [2, 0]& [4, 2]& [3, 0]& [0, 0]& \\
\end{bmatrix}

2. Quel est le chemin le plus court du sommet 4 au sommet 3?

    **Answer**
    
    According to the final matrix of previous question, we look at the element in $4_{th}$ row $3_{rd}$ column, which is the value paire of $(5,5)$, indicating the shortest distance is $5$, and the path goes through the $5_{th}$ node.

    Again in this matrix, we search the element in $4_{th}$ row $5_{th}$ column and the element in $5_{th}$ row $3_{rd}$ column, which are $(1,0)$ and $(4,2)$, respectively. $k$ in first value pair is $0$, meaning that the shortest path between them is the edge that connect them directly. $k$ in second value pair is $2$, meaning that $2_{nd}$ node is a node within the shortest path, we repeat the search for shortest sub-path again and again until all value paire has the $k=0$. 

    Finally, we got shortest path from node4 to node5:
    $$4 \rightarrow 5  \rightarrow   2  \rightarrow  1 \rightarrow  3$$
    ,and the shortest distance is 5.

3. Remplisser le tableau suivant afin que l’on connaisse l’ordre de multiplications des matrice qui minimuse le nombre de multiplication. Dans la case $(i, j)$ mettez le nombre miniumum de multiplications $m_{i,j}$ nécessaire pour cacluler le produit des matrices $M_i M_{i+1}\cdots M_j$ ainsi que l’endroit où on coupe pour obtenir ce minimum:$(m_{i,j}, k)$.

   Les dimensions de matrices sont $[3,14,2,17,6,2]$
    
   **Answer**
    
   \begin{bmatrix}
       0,0 & 84,0  & 186,2 & 324,2 & 324,2\\
           &  0,0  & 476,0 & 372,2 & 284,2\\
           &       &   0,0 & 204,0 & 228,4\\
           &       &       &  0,0  & 204,0\\
           &       &       &     &  0,0\\
   \end{bmatrix}
   **Note**:$k=0$ means there is no division for the calculation.
   
   Here is how I got the result:
   
   **Assume**: the result matrix is $m$; the dimension list is $d$; the indices for row and column start from 1, and the index for dimensions starts from 0. 
   
   From the length of dimensions, we know it's the multiplication of 5 matrices: $M_1 M_2 M_3 M_4 M_5$.
   
   **step1**: for $1\le i \le5$, set $m[i,i] = 0$
   
   **step2**: set $s = 1$, let $m[i,i+s] = d[i-1]\times d[i] \times d[i+1]$, we got: 
    \begin{align*}
    m[1,2] &= d[0]\times d[1] \times d[2] =  3\times 14 \times 2 &= 84\\
    m[2,3] &= d[1]\times d[2] \times d[3] = 14\times 2 \times 17 &= 476\\
    m[3,4] &= d[2]\times d[3] \times d[4] = 2\times 17 \times 6 &= 204\\
    m[4,5] &= d[3]\times d[4] \times d[5] = 17\times 6 \times 2 &= 204\\
    \end{align*}
    
    **step3**: for $s=2,3,4$, let 
    \begin{align*}
    m[i,i+s] = \min_{i \le k < i+s} \left( m[i,k] + m[k+1,i+s] + d[i-1]\times d[k] \times d[i+s] \right)
    \end{align*}

    Therefore,
    \begin{align*}
    m[1,3] &= \min ( m[1,1] + m[2,3] + d[0]d[1]d[3] = 0 + 476 + 714 = 1190 \ (k=1)\\
           &\quad\quad\quad m[1,2] + m[3,3] + d[0]d[2]d[3] = 84 + 0 + 102  = 186 \ (k=2))\\
           &= 186\ (k=2) \\
    m[2,4] &= \min ( m[2,2] + m[3,4] + d[1]d[2]d[4] = 0 + 204 + 168 = 372 \ (k=2)\\
             &\quad\quad\quad  m[2,3] + m[4,4] + d[1]d[3]d[4] = 476 + \cdots > 372 \ (k=3))\\
           &= 372\ (k=2)\\ 
    m[3,5] &= \min ( m[3,3] + m[4,5] + d[2]d[3]d[5] = 0 + 204 + 68 = 272 \ (k=3)\\
             &\quad\quad\quad  m[3,4] + m[5,5] + d[2]d[4]d[5] = 204 + 0 +24 =228 \ (k=4))\\
           &= 228\ (k=4)\\       
    m[1,4] &= \min ( m[1,1] + m[2,4] + d[0]d[1]d[4] = 0 + 372 + 252 = 624 \ (k=1)\\
             &\quad\quad\quad  m[1,2] + m[3,4] + d[0]d[2]d[4] = 84 + 204 +36 =324 \ (k=2)\\
             &\quad\quad\quad  m[1,3] + m[4,4] + d[0]d[3]d[4] = 186 + 0 +306 =492 \ (k=3))\\
           &= 324\ (k=2)\\       
    m[2,5] &= \min ( m[2,2] + m[3,5] + d[1]d[2]d[5] = 0 + 228 + 56 = 284 \ (k=2)\\
             &\quad\quad\quad  m[2,3] + m[4,5] + d[1]d[3]d[5] = 476 +\cdots >284 \ (k=3)\\
             &\quad\quad\quad  m[2,4] + m[5,5] + d[1]d[4]d[5] = 372 +\cdots >284 \ (k=4))\\
           &= 284\ (k=2)\\
    m[1,5] &= \min ( m[1,1] + m[2,5] + d[0]d[1]d[5] = 0 + 284 + 84 = 368 \ (k=1)\\
             &\quad\quad\quad  m[1,2] + m[3,5] + d[0]d[2]d[5] = 84 +228 +12 =324 \ (k=2)\\
             &\quad\quad\quad  m[1,3] + m[4,5] + d[0]d[3]d[5] = 186 +204 + 102 =492 \ (k=3)\\
             &\quad\quad\quad  m[1,4] + m[5,5] + d[0]d[4]d[5] = 324 + 0 + 36 = 360 \ (k=4))\\
           &= 324\ (k=2)\\
    \end{align*}

4. Quel est l’ordre optimal des multiplications et quel est le nombre de multiplications minimum?

   **Answer**
   From result of previous question, the following division of the matrix multiplication is optimal:
   
   \begin{align*}
   M_1 M_2 M_3 M_4 M_5 &= (M_1 M_2)(M_3 M_4 M_5) & (k=2 \text{ for } m[1,5])\\
                       &= (M_1 M_2)(M_3 M_4)(M_5) & (k=4 \text{ for } m[3,5])\\
   \end{align*}
   
   And, the minimal number of multiplication is $m[1,5] = 324$

<hr>

In [1]:
# codes for question 1-2
import numpy as np

def print_d_p(D, p):
    n = D.shape[0]
    for i in range(n):
        for j in range(n):
            d = "\infty" if D[i,j] == float("inf") else int(D[i,j])
            path = int(p[i,j])
            print("[{}, {}]".format(d, path),end = "& ")
        print("\\\\")
    
def Floyd(L):
    #D = copy.copy(L)
    D = np.array(L)
    p = np.zeros_like(D) # chemin
    n = D.shape[0]  # number of nodes
    for k in range(n):
        for i in range(n):
            for j in range(n):
                if D[i,k]+D[k,j]< D[i,j]:
                    p[i,j] = k+1
                D[i,j] = min(D[i,j], D[i,k] + D[k,j])
                
        print("iter{}".format(k+1))
        print_d_p(D, p)
    return D, p

In [2]:
# matrix of the exercise
L = np.array([
     [0, float("inf"), 1, 6, 4],
     [1, 0, float("inf"), float("inf"), 5],
     [float("inf"), float("inf"), 0, 1, 5],
     [float("inf"), 5, float("inf"), 0, 1],
     [float("inf"), 2, float("inf"), 3, 0]
    ])

# matrix from the book
L2 = np.array([ 
    [0, 5, float('inf'), float('inf')],
    [50, 0, 15, 5],
    [30, float('inf'), 0, 15],
    [15, float('inf'), 5, 0]
])

In [3]:
d, p = Floyd(L)

iter1
[0, 0]& [\infty, 0]& [1, 0]& [6, 0]& [4, 0]& \\
[1, 0]& [0, 0]& [2, 1]& [7, 1]& [5, 0]& \\
[\infty, 0]& [\infty, 0]& [0, 0]& [1, 0]& [5, 0]& \\
[\infty, 0]& [5, 0]& [\infty, 0]& [0, 0]& [1, 0]& \\
[\infty, 0]& [2, 0]& [\infty, 0]& [3, 0]& [0, 0]& \\
iter2
[0, 0]& [\infty, 0]& [1, 0]& [6, 0]& [4, 0]& \\
[1, 0]& [0, 0]& [2, 1]& [7, 1]& [5, 0]& \\
[\infty, 0]& [\infty, 0]& [0, 0]& [1, 0]& [5, 0]& \\
[6, 2]& [5, 0]& [7, 2]& [0, 0]& [1, 0]& \\
[3, 2]& [2, 0]& [4, 2]& [3, 0]& [0, 0]& \\
iter3
[0, 0]& [\infty, 0]& [1, 0]& [2, 3]& [4, 0]& \\
[1, 0]& [0, 0]& [2, 1]& [3, 3]& [5, 0]& \\
[\infty, 0]& [\infty, 0]& [0, 0]& [1, 0]& [5, 0]& \\
[6, 2]& [5, 0]& [7, 2]& [0, 0]& [1, 0]& \\
[3, 2]& [2, 0]& [4, 2]& [3, 0]& [0, 0]& \\
iter4
[0, 0]& [7, 4]& [1, 0]& [2, 3]& [3, 4]& \\
[1, 0]& [0, 0]& [2, 1]& [3, 3]& [4, 4]& \\
[7, 4]& [6, 4]& [0, 0]& [1, 0]& [2, 4]& \\
[6, 2]& [5, 0]& [7, 2]& [0, 0]& [1, 0]& \\
[3, 2]& [2, 0]& [4, 2]& [3, 0]& [0, 0]& \\
iter5
[0, 0]& [5, 5]& [1, 0]& [2, 3]& [3, 4]& \\
[1

<hr>

In [3]:
import numpy as np
# codes for question 3-4
d = [3, 14, 2, 17, 6, 2] # dimensions
#d = [5, 6, 7, 45, 3, 25]
n = len(d) - 1 # number of matrices

m = np.zeros((n,n))
for i in range(n):
    m[i,i] = 0
    s = 1
    if i+s< n:
        m[i,i+s] = d[i]*d[i+1]*d[i+2]

print(m)

[[  0.  84.   0.   0.   0.]
 [  0.   0. 476.   0.   0.]
 [  0.   0.   0. 204.   0.]
 [  0.   0.   0.   0. 204.]
 [  0.   0.   0.   0.   0.]]


In [4]:
for s in range(2, n):
    for i in range(n):
        if i + s < n:
            temps = []
            for k in range(i, i+s):
                cals = m[i,k] + m[k+1, i+s] + d[i]*d[k+1]*d[i+s+1]
                temps.append(cals)
            m[i,i+s] = min(temps)
    print(m)
    print()

[[  0.  84. 186.   0.   0.]
 [  0.   0. 476. 372.   0.]
 [  0.   0.   0. 204. 228.]
 [  0.   0.   0.   0. 204.]
 [  0.   0.   0.   0.   0.]]

[[  0.  84. 186. 324.   0.]
 [  0.   0. 476. 372. 284.]
 [  0.   0.   0. 204. 228.]
 [  0.   0.   0.   0. 204.]
 [  0.   0.   0.   0.   0.]]

[[  0.  84. 186. 324. 324.]
 [  0.   0. 476. 372. 284.]
 [  0.   0.   0. 204. 228.]
 [  0.   0.   0.   0. 204.]
 [  0.   0.   0.   0.   0.]]

